version: '3'
services:
  reqdoc:
    env_file:
      - .env
    build: .
    ports:
      - "8080:${SERVICE_PORT}"
  app:
    env_file:
      - .env
    build: ./app
    depends_on:
      - reqdoc
    ports:
      - "3000:3000"